#Thank You For Downloading My Plugin
# -Skiddy
# {pname} - Player Name
# {tps} - Tps Server
# {health} - Player Health
# {rank} - Rank Of Player (Need PurePerms)
# {money} - Money Of Player (Need EconomyAPI)
# {online} - Online Players
# {date} - Date
# {hour} - Hour
# {seconds} - Seconds
# {minute} - Minute
# {space} - Always Use This When Creating New Line!
# {line} - Line
ScoreBoard: " {space} Welcome {pname}"
